name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code                        # step 1
      uses: actions/checkout@v4      
    - name: Set Node.js                              # step 2
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install dependencies                     # step 3
      run: npm install
    - name: execute tests                            # step 4
      run: npm test
    - run: npm ci                                    # step 5
    - run: npm run build --if-present                # step 6
    - name: Execute integration tests			           # step 7
      run: npm run test   
      

      