name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:					# set matrix strategy for different Node.js versions
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout the code                        # step 1
      uses: actions/checkout@v4      
    - name: Set Node.js                              # step 2
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}     # set execute the job for all version in the matrix
    - name: install dependencies                     # step 3
      run: npm install
    - name: execute tests                            # step 4
      run: npm test
    - run: npm ci                                    # step 5
    - run: npm run build --if-present                # step 6
    - name: Execute integration tests			           # step 7
      run: npm run test   